Repository Refemi/refemi_front, pull requests merged in 2022-02, with the labels that each got.

#66 updated date to make it dynamic
  src/components/Footer/Footer.jsx
Labels: enhancement, to be tested plaese!

#65 clickable themes in ListReference
  src/components/ListReferences.jsx
  src/styles/css/style.css
  src/styles/sass/base/_base.scss
  src/styles/sass/main.scss
  src/views/References.jsx
Labels: to be tested plaese!

#76 fix: recovery variable from asynchronous function
  src/views/Connection.jsx
Labels: bug

#74 update: show on the screen which error is involved
  src/views/References.jsx
Labels: enhancement
