Repository Refemi/refemi_front, pull requests merged in 2022-03, with the labels that each got.

#78 Fix bug in the dashboard counter
  src/components/Dashboard/ContentDashboard/HeaderDashboard.jsx
Labels: bug

#77 22 verify that reference doesnt exist
  src/components/Dashboard/FormDashboard/FormReference.jsx
  src/styles/css/style.css
  src/styles/sass/sasscomponents/_addReference.scss
  src/styles/sass/views/_dashboard.scss
Labels: enhancement, to be tested plaese!

#86 updated homepage text
  src/views/Home.jsx
Labels: to be tested plaese!

#89 unnecessary hovers removed
  src/components/ListReferences.jsx
  src/styles/css/style.css
  src/styles/sass/base/_base.scss
  src/views/Home.jsx
Labels: to be tested plaese!

#90 removed image from suggestion form and from ref sheet (only commented…
  src/components/Dashboard/FormDashboard/FormReference.jsx
  src/views/RefSheet.jsx
Labels: to be tested plaese!

#91 send array of themes to backend
  src/components/Dashboard/FormDashboard/FormReference.jsx
Labels: to be tested plaese!

#93 fixed switch options for categories en new reference form
  src/components/Dashboard/FormDashboard/SelectReference.jsx
Labels: to be tested plaese!
