Repository Refemi/refemi_front, pull requests merged in 2022-01, with the labels that each got.

#34 19 general sass
  package.json
  public/index.html
  src/App.css
  src/App.jsx
  src/components/Button/Button.jsx
  src/components/Counter.jsx
  src/components/Dashboard/ContentDashboard/ContributionsDashboard.jsx
  src/components/Dashboard/ContentDashboard/HeaderDashboard.jsx
  src/components/Dashboard/ContentDashboard/MainDashboard.jsx
  src/components/Dashboard/FormDashboard/AddReference.jsx
  src/components/Dashboard/FormDashboard/FormReference.jsx
  src/components/Dashboard/FormDashboard/SelectReference.jsx
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/components/Header/Navbar.css
  src/components/Header/Navbar.jsx
  src/components/ListReferences.jsx
  src/components/SearchBar/SearchBar.css
  src/components/SearchBar/SearchResult.jsx
  src/components/WidgetCat.jsx
  src/css/categories.css
  src/css/contact.css
  src/css/counter.css
  src/css/dashboard.css
  src/css/forms.css
  src/css/home.css
  src/css/references.css
  src/css/refsheet.css
  src/css/themes.css
  src/css/widget.css
  src/styles/css/style.css
  src/styles/sass/abstract/_mixins.scss
  src/styles/sass/abstract/_variables.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/layout/_footer.scss
  src/styles/sass/layout/_header.scss
  src/styles/sass/main.scss
  src/styles/sass/sasscomponents/_addReference.scss
  src/styles/sass/sasscomponents/_counter.scss
  src/styles/sass/sasscomponents/_refSheet.scss
  src/styles/sass/sasscomponents/_widget.scss
  src/styles/sass/views/_categories.scss
  src/styles/sass/views/_dashboard.scss
  src/styles/sass/views/_home.scss
  src/styles/sass/views/_references.scss
  src/styles/sass/views/_search.scss
  src/styles/sass/views/_themes.scss
  src/views/Categories.jsx
  src/views/Connection.jsx
  src/views/Contact.jsx
  src/views/Dashboard.jsx
  src/views/Home.jsx
  src/views/RefSheet.jsx
  src/views/References.jsx
  src/views/Search.jsx
  src/views/Themes.jsx
Labels: to be tested plaese!

#37 00 little fixes
  src/App.jsx
  src/components/Header/Header.jsx
  src/components/SearchBar/SearchResult.jsx
  src/fonts/antique_book_cover.otf
  src/styles/css/style.css
  src/styles/sass/abstract/_variables.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/sasscomponents/_refSheet.scss
  src/styles/sass/sasscomponents/_widget.scss
  src/styles/sass/views/_references.scss
  src/styles/sass/views/_search.scss
  src/views/RefSheet.jsx
  src/views/References.jsx
  src/views/Search.jsx
  src/views/Themes.jsx
Labels: to be tested plaese!

#38 05 pagination
  package.json
  src/components/ListReferences.jsx
  src/components/SearchBar/SearchResult.jsx
  src/styles/css/style.css
  src/styles/sass/layout/_header.scss
  src/styles/sass/sasscomponents/_widget.scss
  src/styles/sass/views/_references.scss
  src/views/References.jsx
  src/views/Search.jsx
Labels: to be tested plaese!

#47 46-modify-routes-following-api-refactoing
  src/App.jsx
  src/components/Dashboard/ContentDashboard/ContributionsDashboard.jsx
  src/components/Dashboard/ContentDashboard/HeaderDashboard.jsx
  src/components/Dashboard/ContentDashboard/MainDashboard.jsx
  src/components/Dashboard/FormDashboard/AddReference.jsx
  src/components/Dashboard/FormDashboard/FormReference.jsx
  src/components/Dashboard/FormDashboard/SelectReference.jsx
  src/components/Header/Navbar.jsx
  src/components/ListReferences.jsx
  src/components/WidgetCat.jsx
  src/services/authHeader.js
  src/services/http-common.js
  src/views/Categories.jsx
  src/views/Connection.jsx
  src/views/Dashboard.jsx
  src/views/Home.jsx
  src/views/References.jsx
  src/views/Themes.jsx
Labels: refactoring

#48 Show error messages when login
  src/App.jsx
  src/components/Dashboard/ContentDashboard/ContributionsDashboard.jsx
  src/components/Dashboard/ContentDashboard/HeaderDashboard.jsx
  src/components/Dashboard/FormDashboard/AddReference.jsx
  src/components/Dashboard/FormDashboard/SelectReference.jsx
  src/components/SearchBar/SearchResult.jsx
  src/services/http-common.js
  src/styles/css/style.css
  src/styles/sass/abstract/_variables.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/main.scss
  src/styles/sass/views/_auth.scss
  src/views/Connection.jsx
  src/views/Dashboard.jsx
  src/views/Home.jsx
  src/views/RefSheet.jsx
  src/views/References.jsx
Labels: code level up, to be tested plaese!

#49 23 create a loader
  src/App.jsx
  src/components/Loader.jsx
  src/components/SearchBar/SearchResult.jsx
  src/styles/css/style.css
  src/styles/sass/abstract/_keyframes.scss
  src/styles/sass/abstract/_mixins.scss
  src/styles/sass/base/_base.scss
  src/styles/sass/main.scss
  src/views/Connection.jsx
  src/views/Dashboard.jsx
  src/views/References.jsx
  src/views/Search.jsx
Labels: to be tested plaese!, priority: cool

#58 43 404 page
  src/components/Button/Button.jsx
  src/components/Button/index.js
  src/components/Error.jsx
  src/styles/css/style.css
  src/styles/sass/main.scss
  src/styles/sass/sasscomponents/_error.scss
  src/views/Categories.jsx
  src/views/Home.jsx
  src/views/RefSheet.jsx
  src/views/References.jsx
  src/views/Themes.jsx
Labels: feature

#61 clean in References component
  package.json
  src/components/ListReferences.jsx
  src/views/References.jsx
Labels: to be tested plaese!

#57 55 content retrieval bug in the form
  src/components/Dashboard/ContentDashboard/ContributionsDashboard.jsx
  src/components/Dashboard/ContentDashboard/MainDashboard.jsx
  src/components/Dashboard/FormDashboard/AddReference.jsx
  src/components/Dashboard/FormDashboard/FormReference.jsx
Labels: bug

#63 56 fix widget categories anchors
  package.json
  src/components/Dashboard/ContentDashboard/MainDashboard.jsx
  src/components/WidgetCat.jsx
  src/views/Dashboard.jsx
  src/views/References.jsx
Labels: bug, to be tested plaese!

#70 removed fixed position from ffooter
  src/styles/css/style.css
  src/styles/sass/layout/_footer.scss
  src/styles/sass/main.scss
Labels: bug, design, to be tested plaese!
